apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\bruck\OneDrive - University of Pittsburgh\classes\cs1660\cs1660\Project\kompose-windows-amd64.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  type: LoadBalancer
  ports:
    - port: 50070
      targetPort: 50070
  selector:
    io.kompose.service: namenode
status:
  loadBalancer: {}
