apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\bruck\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: spark
  name: spark
spec:
  containers:
    - env:
        - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_MODE
          value: master
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        - name: SPARK_RPC_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_SSL_ENABLED
          value: "no"
      image: docker.io/bitnami/spark:3
      name: spark
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: Always
