apiVersion: v1
kind: Pod
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  containers:
    - image: brucker/sonar2b
      name: sonar
      ports:
        - containerPort: 9000
      resources:
        requests:
          memory: 2Gi