apiVersion: v1
kind: Pod
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  containers:
    - image: sonarsource/sonar-scanner-cli
      name: sonarscanner
      args: ["--rm",
             "-e SONAR_HOST_URL=\"http://localhost\"",
             "-e SONAR_LOGIN=\"admin\"",
            #  "-v \"${YOUR_REPO}:/usr/src\"",
             "sonarsource/sonar-scanner-cli"]
    - image: sonarqube
      name: sonarqube
