apiVersion: apps/v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Users\bruck\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker
spec:
  containers:
    - env:
        - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_MASTER_URL
          value: spark:7077
        - name: SPARK_MODE
          value: worker
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        - name: SPARK_RPC_ENCRYPTION_ENABLED
          value: "no"
        - name: SPARK_SSL_ENABLED
          value: "no"
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: 1G
      image: docker.io/bitnami/spark:3
      name: spark-worker
      resources: {}
  restartPolicy: Always
