apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\bruck\Downloads\kompose-windows-amd64.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: sonarqube
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarqube
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\bruck\Downloads\kompose-windows-amd64.exe convert
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: sonarqube
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: SONARQUBE_DATABASE_HOST
              value: postgresql
            - name: SONARQUBE_DATABASE_NAME
              value: bitnami_sonarqube
            - name: SONARQUBE_DATABASE_PORT_NUMBER
              value: "5432"
            - name: SONARQUBE_DATABASE_USER
              value: bn_sonarqube
          image: docker.io/bitnami/sonarqube:9
          name: sonarqube
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/sonarqube
              name: downloads-sonarqube-data
      restartPolicy: Always
      volumes:
        - name: downloads-sonarqube-data
          persistentVolumeClaim:
            claimName: downloads-sonarqube-data
status: {}
